#version: '3.8' #check if there is a new docker compose version
name: paraisochui #this is the name of your project, you can change it if you want
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        - LOCAL_SSL_NAME=${LOCAL_SSL_NAME:-paraisochui-val}
    #image: php:8.4-apache #check the php version you need for your project
    hostname: paraisochui
    ports:
      - "80:80" #this line maps your pc port to the container port
      - "443:443" #this line maps your pc port to the container port
    volumes:
      - ./public_html:/var/www/html
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
